config/routes.rb
Knobblossom2::Application.routes.draw do
  resources :project_photos

  resources :projects

  resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/project_photo.rb
class ProjectPhoto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/project_photos_controller.rb
class ProjectPhotosController < ApplicationController
  # GET /project_photos
  # GET /project_photos.json
  def index
    @project_photos = ProjectPhoto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_photos }
    end
  end

  # GET /project_photos/1
  # GET /project_photos/1.json
  def show
    @project_photo = ProjectPhoto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_photo }
    end
  end

  # GET /project_photos/new
  # GET /project_photos/new.json
  def new
    @project_photo = ProjectPhoto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_photo }
    end
  end

  # GET /project_photos/1/edit
  def edit
    @project_photo = ProjectPhoto.find(params[:id])
  end

  # POST /project_photos
  # POST /project_photos.json
  def create
    @project_photo = ProjectPhoto.new(params[:project_photo])

    respond_to do |format|
      if @project_photo.save
        format.html { redirect_to @project_photo, notice: 'Project photo was successfully created.' }
        format.json { render json: @project_photo, status: :created, location: @project_photo }
      else
        format.html { render action: "new" }
        format.json { render json: @project_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_photos/1
  # PUT /project_photos/1.json
  def update
    @project_photo = ProjectPhoto.find(params[:id])

    respond_to do |format|
      if @project_photo.update_attributes(params[:project_photo])
        format.html { redirect_to @project_photo, notice: 'Project photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_photos/1
  # DELETE /project_photos/1.json
  def destroy
    @project_photo = ProjectPhoto.find(params[:id])
    @project_photo.destroy

    respond_to do |format|
      format.html { redirect_to project_photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/project_photos_helper.rb
module ProjectPhotosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Knobblossom2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :workinprogress %><br />
    <%= f.check_box :workinprogress %>
  </div>
  <div class="field">
    <%= f.label :filename %><br />
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Workinprogress</th>
    <th>Filename</th>
    <th>Caption</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.workinprogress %></td>
    <td><%= photo.filename %></td>
    <td><%= photo.caption %></td>
    <td><%= photo.description %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Workinprogress:</b>
  <%= @photo.workinprogress %>
</p>

<p>
  <b>Filename:</b>
  <%= @photo.filename %>
</p>

<p>
  <b>Caption:</b>
  <%= @photo.caption %>
</p>

<p>
  <b>Description:</b>
  <%= @photo.description %>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/project_photos/_form.html.erb
<%= form_for(@project_photo) do |f| %>
  <% if @project_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_photo.errors.count, "error") %> prohibited this project_photo from being saved:</h2>

      <ul>
      <% @project_photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :photo_id %><br />
    <%= f.number_field :photo_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_photos/edit.html.erb
<h1>Editing project_photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_photo %> |
<%= link_to 'Back', project_photos_path %>

app/views/project_photos/index.html.erb
<h1>Listing project_photos</h1>

<table>
  <tr>
    <th>Project</th>
    <th>Photo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_photos.each do |project_photo| %>
  <tr>
    <td><%= project_photo.project_id %></td>
    <td><%= project_photo.photo_id %></td>
    <td><%= link_to 'Show', project_photo %></td>
    <td><%= link_to 'Edit', edit_project_photo_path(project_photo) %></td>
    <td><%= link_to 'Destroy', project_photo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project photo', new_project_photo_path %>

app/views/project_photos/new.html.erb
<h1>New project_photo</h1>

<%= render 'form' %>

<%= link_to 'Back', project_photos_path %>

app/views/project_photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project:</b>
  <%= @project_photo.project_id %>
</p>

<p>
  <b>Photo:</b>
  <%= @project_photo.photo_id %>
</p>


<%= link_to 'Edit', edit_project_photo_path(@project_photo) %> |
<%= link_to 'Back', project_photos_path %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.description %></td>
    <td><%= project.start_date %></td>
    <td><%= project.end_date %></td>
    <td><%= project.price %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Start date:</b>
  <%= @project.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @project.end_date %>
</p>

<p>
  <b>Price:</b>
  <%= @project.price %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>